# Reviewed and optimized: 2026-02-19
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cd-listener
spec:
  serviceAccountName: pipeline  # For service authentication
  triggers:
    - bindings:
      - ref: cd-binding
      template:
        ref: cd-template
...
